"""
Ecosystem scenario pool for the Ecosystem Tester.

Every entry describes a real business / role / life situation that naturally
requires multiple connected apps (3–7). Descriptions are written in plain
English as a non-technical user would type them into the Physis
Ecosystem Builder. Industries, user types, and suggested app counts vary
across the pool so batch runs exercise the full space.

Shape of each scenario:
    {
        "description":          str,
        "suggested_app_count":  int,   # 3 or 7
        "industry":             str,
        "user_type":            str,
    }

Drawn via get_ecosystem_scenarios(count) — random.sample, no repeats within
a batch, stable ordering preserved so the pool size check is easy.
"""

import random


# ─────────────────────────────────────────────────────────────────────────────
# SMALL BUSINESS — 110 scenarios
# Owner/operator voice. Each scenario implies at least 3 connected apps.
# ─────────────────────────────────────────────────────────────────────────────

SMALL_BUSINESS = [
    ("I run a personal training studio and need a client intake form, a custom workout plan generator, and a progress tracker that sees everything together", 3, "fitness", "small business owner"),
    ("I'm a realtor and need a lead tracker, a property analyzer, and a client follow-up assistant all sharing the same contacts", 3, "real estate", "small business owner"),
    ("I own a neighborhood restaurant and need a reservation manager, a menu performance analyzer, and a staff scheduler", 3, "food", "small business owner"),
    ("Small law firm here — we need a case tracker, a document summarizer, and a client billing assistant tied together", 3, "legal", "small business owner"),
    ("I run a solo accounting practice and need an expense tracker, an invoice generator, and a tax document analyzer", 3, "finance", "small business owner"),
    ("We're a five-person marketing agency — content generator, campaign tracker, and client reporting tool all under one roof", 3, "marketing", "small business owner"),
    ("Photography studio owner — I need a booking manager, a portfolio generator, and an invoice creator", 3, "creative services", "small business owner"),
    ("Dental office manager here — appointment tracker, patient follow-up assistant, and insurance claim analyzer", 3, "healthcare", "small business owner"),
    ("I own a veterinary clinic and need a pet health tracker, appointment scheduler, and medication reminder for our clients", 3, "healthcare", "small business owner"),
    ("I run a hair salon — appointment manager, style recommendation assistant, and product inventory tracker", 3, "beauty", "small business owner"),
    ("Auto repair shop owner — work order tracker, parts inventory manager, and customer follow-up assistant", 3, "automotive", "small business owner"),
    ("I run a cleaning company — job scheduler, supply tracker, and customer feedback collector", 3, "home services", "small business owner"),
    ("Landscaping business owner — project planner, equipment tracker, and seasonal schedule generator", 3, "home services", "small business owner"),
    ("I'm a wedding planner — vendor tracker, timeline generator, and budget analyzer for each couple", 3, "events", "small business owner"),
    ("Catering business owner — menu generator, event planner, and ingredient cost calculator", 3, "food", "small business owner"),
    ("I run a food truck — daily location planner, inventory tracker, and customer loyalty tracker", 3, "food", "small business owner"),
    ("Neighborhood bakery owner — custom cake order tracker, ingredient inventory, and daily production planner", 3, "food", "small business owner"),
    ("Coffee shop owner — inventory tracker, staff scheduler, and customer feedback analyzer", 3, "food", "small business owner"),
    ("I run a small gym — member tracker, class scheduler, and workout plan generator for trainers", 3, "fitness", "small business owner"),
    ("Yoga studio owner — class schedule manager, member attendance tracker, and instructor schedule assistant", 3, "fitness", "small business owner"),
    ("Pilates studio — client progress tracker, reformer-class scheduler, and private session billing", 3, "fitness", "small business owner"),
    ("Martial arts studio owner — student belt progression tracker, class scheduler, and parent communication assistant", 3, "fitness", "small business owner"),
    ("CrossFit box owner — workout-of-the-day planner, member performance tracker, and competition prep assistant", 3, "fitness", "small business owner"),
    ("Tennis club owner — court booking manager, lesson scheduler, and member tournament tracker", 3, "fitness", "small business owner"),
    ("Swim school — lesson scheduler, student skill progression tracker, and parent notification assistant", 3, "fitness", "small business owner"),
    ("Music school — student practice tracker, lesson scheduler, and recital planner", 3, "arts", "small business owner"),
    ("Dance studio owner — class registration, recital planner, costume tracker, ticket sales, and parent messaging — we need everything connected", 7, "arts", "small business owner"),
    ("I run an art studio — class enrollment, supply inventory, and student portfolio showcase", 3, "arts", "small business owner"),
    ("Pottery studio — kiln firing scheduler, student project tracker, and class enrollment manager", 3, "arts", "small business owner"),
    ("Cooking class business — class scheduler, recipe manager, and ingredient order tracker", 3, "food", "small business owner"),
    ("Airbnb host with three properties — booking tracker, cleaning scheduler, and guest communication assistant", 3, "hospitality", "small business owner"),
    ("Vacation rental manager with a portfolio of twelve homes — I need booking coordination, cleaning schedule, maintenance tracker, owner reporting, pricing analyzer, guest messaging, and review follow-up", 7, "hospitality", "small business owner"),
    ("Bed and breakfast owner — reservation manager, breakfast menu planner, and guest feedback tracker", 3, "hospitality", "small business owner"),
    ("Boutique hotel manager — booking, housekeeping schedule, concierge guide, revenue analyzer, guest messaging, maintenance tracker, and review responder", 7, "hospitality", "small business owner"),
    ("Tour company owner — tour booking, guide schedule, and customer review tracker", 3, "travel", "small business owner"),
    ("Fishing charter captain — trip booking, weather planner, and customer follow-up assistant", 3, "travel", "small business owner"),
    ("Ski instructor who runs a small school — lesson booking, snow report assistant, and student progress tracker", 3, "fitness", "small business owner"),
    ("Horseback riding stable — lesson scheduler, horse care tracker, and client progress assistant", 3, "fitness", "small business owner"),
    ("Surf school owner — lesson booking, tide and forecast planner, and student progress tracker", 3, "fitness", "small business owner"),
    ("SUP rental shop — hourly booking, equipment tracker, and weather advisor", 3, "fitness", "small business owner"),
    ("Plumber who runs a small team — job dispatch, parts inventory, and customer follow-up assistant", 3, "home services", "small business owner"),
    ("Electrician — work order tracker, tool inventory, and invoice generator", 3, "home services", "small business owner"),
    ("Carpenter who takes custom jobs — project tracker, material cost calculator, and quote generator", 3, "home services", "small business owner"),
    ("House painter — quote generator, project scheduler, and paint inventory tracker", 3, "home services", "small business owner"),
    ("Roofer — estimate generator, crew scheduler, material order tracker, warranty tracker, customer communication, referral tracker, and post-job follow-up assistant", 7, "home services", "small business owner"),
    ("HVAC contractor — maintenance scheduler, parts inventory, and customer follow-up assistant", 3, "home services", "small business owner"),
    ("Flooring installer — quote generator, project scheduler, and material order tracker", 3, "home services", "small business owner"),
    ("Tile installer — job scheduler, material calculator, and customer gallery showcase", 3, "home services", "small business owner"),
    ("Handyman — job scheduler, tool inventory, and invoice creator", 3, "home services", "small business owner"),
    ("Pest control business — treatment scheduler, chemical inventory, and recurring customer tracker", 3, "home services", "small business owner"),
    ("Dog walker — walk scheduler, client pet profile tracker, and invoice generator", 3, "pets", "small business owner"),
    ("Pet sitter — booking calendar, pet care notes tracker, and post-visit report generator", 3, "pets", "small business owner"),
    ("Dog groomer — appointment scheduler, pet profile tracker, and product inventory assistant", 3, "pets", "small business owner"),
    ("Dog trainer — session scheduler, student progress tracker, and training plan generator", 3, "pets", "small business owner"),
    ("Pet boarding facility — booking manager, feeding schedule tracker, and owner update assistant", 3, "pets", "small business owner"),
    ("Aquarium store — livestock inventory, customer tank-care tracker, and water-quality advisor", 3, "pets", "small business owner"),
    ("Reptile shop owner — livestock inventory, feeding schedule assistant, and customer care tracker", 3, "pets", "small business owner"),
    ("Horse boarding stable — stall assignment tracker, feeding schedule, and vet visit coordinator", 3, "pets", "small business owner"),
    ("Boutique clothing store — inventory tracker, customer loyalty program, and window display planner", 3, "retail", "small business owner"),
    ("Shoe repair shop — work order tracker, pickup reminder, and customer history assistant", 3, "retail", "small business owner"),
    ("Jewelry store owner — inventory manager, repair tracker, and customer appraisal follow-up", 3, "retail", "small business owner"),
    ("Antique shop — inventory tracker, appraisal log, and customer wishlist assistant", 3, "retail", "small business owner"),
    ("Vintage clothing store — inventory tracker, consignment manager, and Instagram content planner", 3, "retail", "small business owner"),
    ("Consignment shop owner — item intake tracker, payout calculator, and customer notifications", 3, "retail", "small business owner"),
    ("Craft supply store — inventory tracker, class scheduler, and customer loyalty program", 3, "retail", "small business owner"),
    ("Fabric store — inventory tracker, cutting order manager, and class scheduler", 3, "retail", "small business owner"),
    ("Gift shop owner — seasonal inventory tracker, window-display planner, and customer loyalty program", 3, "retail", "small business owner"),
    ("Flower shop — order tracker, delivery scheduler, and seasonal catalog generator", 3, "retail", "small business owner"),
    ("Local bookstore — inventory tracker, book club scheduler, and event planner", 3, "retail", "small business owner"),
    ("Comic book shop — new-release tracker, customer pull-list manager, and tournament scheduler", 3, "retail", "small business owner"),
    ("Board game store — inventory tracker, game-night scheduler, and customer demo reservation", 3, "retail", "small business owner"),
    ("Record store — inventory tracker, customer wishlist, and in-store event planner", 3, "retail", "small business owner"),
    ("Musical instrument shop — inventory tracker, repair job tracker, and lesson scheduler for teachers renting space", 3, "retail", "small business owner"),
    ("Electronics repair shop — work order tracker, parts inventory, and customer pickup notifications", 3, "retail", "small business owner"),
    ("Phone repair kiosk — intake tracker, parts inventory, and warranty tracker", 3, "retail", "small business owner"),
    ("Computer repair shop — service ticket tracker, parts inventory, and customer follow-up assistant", 3, "retail", "small business owner"),
    ("Local bike shop — inventory tracker, repair job tracker, and group-ride planner", 3, "retail", "small business owner"),
    ("Ski shop — rental tracker, repair job queue, and seasonal snow-report assistant", 3, "retail", "small business owner"),
    ("Chiropractic practice — patient appointment tracker, intake form, treatment plan generator, exercise handout creator, insurance claim helper, referral tracker, and follow-up assistant", 7, "healthcare", "small business owner"),
    ("Massage therapist — booking calendar, client intake forms, and session notes tracker", 3, "healthcare", "small business owner"),
    ("Acupuncturist — intake forms, treatment notes tracker, and follow-up scheduler", 3, "healthcare", "small business owner"),
    ("Physical therapy clinic — patient intake, exercise plan generator, and insurance tracker", 3, "healthcare", "small business owner"),
    ("Nutritionist — client intake, meal plan generator, and progress tracker", 3, "healthcare", "small business owner"),
    ("Personal chef — client preference tracker, menu planner, and grocery list generator", 3, "food", "small business owner"),
    ("Private tutor — student roster, lesson planner, and parent progress report generator", 3, "education", "small business owner"),
    ("Driving instructor — student lesson tracker, route planner, and test-prep assistant", 3, "education", "small business owner"),
    ("Youth swim coach who also runs private lessons — student progress tracker, lesson scheduler, and meet-prep assistant", 3, "fitness", "small business owner"),
    ("Private tennis coach — student roster, lesson plan generator, and progress tracker", 3, "fitness", "small business owner"),
    ("Mobile notary — appointment scheduler, document checklist, and client follow-up assistant", 3, "legal", "small business owner"),
    ("Freelance wedding DJ — booking calendar, music request tracker, and timeline generator per event", 3, "events", "small business owner"),
    ("Wedding photographer — booking tracker, shot-list generator, and album delivery manager", 3, "creative services", "small business owner"),
    ("Funeral home director — arrangement tracker, service planner, and family follow-up assistant", 3, "services", "small business owner"),
    ("Independent tax preparer — client intake, document checklist generator, and appointment scheduler", 3, "finance", "small business owner"),
    ("Insurance broker — client quote tracker, policy renewal reminder, and claim assistance tool", 3, "finance", "small business owner"),
    ("Independent financial planner — client portfolio tracker, meeting prep assistant, and annual review planner", 3, "finance", "small business owner"),
    ("Mortgage broker — lead tracker, document collection assistant, and rate watch tool", 3, "finance", "small business owner"),
    ("Bail bond service — case tracker, check-in reminder, and court date notifier", 3, "services", "small business owner"),
    ("Pawn shop owner — inventory tracker, loan tracker, and appraisal helper", 3, "retail", "small business owner"),
    ("Local food delivery service — driver dispatch, order tracker, and customer follow-up assistant", 3, "food", "small business owner"),
    ("Laundromat owner — machine usage tracker, supply inventory, and attendant schedule", 3, "services", "small business owner"),
    ("Dry cleaner — order tracker, pickup reminder, and customer loyalty program", 3, "services", "small business owner"),
    ("Tailor shop — alteration job tracker, pickup reminder, and measurement profile", 3, "services", "small business owner"),
    ("Car wash owner — membership tracker, employee schedule, and supply inventory", 3, "automotive", "small business owner"),
    ("Auto detail shop — booking calendar, supply tracker, and customer history", 3, "automotive", "small business owner"),
    ("Auto rental business — fleet tracker, rental agreement generator, and cleaning schedule", 3, "automotive", "small business owner"),
    ("Boat rental shop — inventory tracker, reservation manager, and safety checklist generator", 3, "travel", "small business owner"),
    ("E-bike rental shop — fleet tracker, hourly booking manager, and maintenance scheduler", 3, "travel", "small business owner"),
    ("Independent bookstore — inventory tracker, book club scheduler, and author event planner", 3, "retail", "small business owner"),
    ("Record label (indie) — artist roster, release calendar, royalty calculator, press outreach tracker, merch inventory, social content planner, and royalty statement generator", 7, "creative services", "small business owner"),
    ("Podcast production studio — episode tracker, guest pipeline, equipment inventory, billing system, sponsor tracker, scheduling, and content promotion planner", 7, "creative services", "small business owner"),
    ("Small brewery — recipe tracker, production scheduler, and retail inventory manager", 3, "food", "small business owner"),
    ("Urban farm CSA — subscriber manager, harvest planner, and weekly share generator", 3, "food", "small business owner"),
    ("Farmers market vendor — inventory tracker, market-day planner, and customer newsletter", 3, "food", "small business owner"),
    ("Food truck owner building a second truck — fleet tracker, menu planner, location scheduler, staff roster, inventory ordering, POS summary, and customer loyalty program", 7, "food", "small business owner"),
    ("Etsy-focused handmade jewelry maker — order tracker, inventory, shipping assistant, review manager, product photography queue, Instagram planner, and monthly reporting", 7, "retail", "small business owner"),
    ("Mobile car detailing service — route planner, booking calendar, and supply tracker", 3, "automotive", "small business owner"),
]


# ─────────────────────────────────────────────────────────────────────────────
# CREATORS & FREELANCERS — 110 scenarios
# Solo or two-person operation. "I'm a ___ and I need..." voice.
# ─────────────────────────────────────────────────────────────────────────────

CREATORS = [
    ("I'm a YouTube creator and need a content idea generator, a video script writer, and an audience analytics tracker", 3, "creator economy", "creator"),
    ("Podcast host — episode planner, guest outreach assistant, and listener feedback analyzer", 3, "creator economy", "creator"),
    ("Freelance writer — article idea generator, client project tracker, and invoice creator", 3, "creative services", "freelancer"),
    ("Freelance graphic designer — project tracker, client feedback collector, and time-billing calculator", 3, "creative services", "freelancer"),
    ("Indie music producer — project tracker, sample library organizer, and royalty calculator", 3, "creative services", "creator"),
    ("I'm a course creator on Teachable — curriculum generator, student progress tracker, and quiz builder", 3, "education", "creator"),
    ("Social media manager for four small brands — content calendar, post performance analyzer, and caption generator", 3, "marketing", "freelancer"),
    ("Etsy seller with 60 SKUs — product description generator, inventory tracker, and customer review analyzer", 3, "retail", "creator"),
    ("Fitness influencer — workout plan generator, nutrition tracker, and brand deal tracker", 3, "creator economy", "creator"),
    ("Travel blogger — trip planner, expense tracker, and content idea generator", 3, "creator economy", "creator"),
    ("Food blogger — recipe tracker, meal-content calendar, and ingredient cost analyzer", 3, "creator economy", "creator"),
    ("Lifestyle blogger — content calendar, affiliate link tracker, and sponsored post manager", 3, "creator economy", "creator"),
    ("Tech YouTuber — product review tracker, script generator, and sponsorship pipeline manager", 3, "creator economy", "creator"),
    ("Gaming streamer — stream schedule, highlight clip manager, and subscriber engagement tracker", 3, "creator economy", "creator"),
    ("Twitch streamer building a community — stream planner, moderator schedule, and subscriber welcome message generator", 3, "creator economy", "creator"),
    ("TikTok creator — trend watcher, content calendar, and caption generator", 3, "creator economy", "creator"),
    ("Instagram Reels creator — content idea generator, post scheduler, and engagement analyzer", 3, "creator economy", "creator"),
    ("OnlyFans creator — content calendar, DM tracker, and fan segmentation assistant", 3, "creator economy", "creator"),
    ("Substack writer — essay idea generator, subscriber feedback tracker, and content calendar", 3, "creator economy", "creator"),
    ("Paid newsletter publisher — subscriber welcome sequence, referral tracker, and issue planner", 3, "creator economy", "creator"),
    ("Freelance illustrator — project tracker, invoice generator, and portfolio updater", 3, "creative services", "freelancer"),
    ("Freelance web designer — project tracker, client feedback collector, and proposal generator", 3, "creative services", "freelancer"),
    ("Freelance logo designer — client brief parser, concept tracker, and invoice creator", 3, "creative services", "freelancer"),
    ("Freelance UX designer — project tracker, research note organizer, and handoff summary generator", 3, "creative services", "freelancer"),
    ("Freelance animator — project tracker, client review collector, and invoice generator", 3, "creative services", "freelancer"),
    ("Freelance 3D modeler — project tracker, asset library organizer, and delivery checklist", 3, "creative services", "freelancer"),
    ("Freelance video editor — project tracker, client feedback collector, and project cost estimator", 3, "creative services", "freelancer"),
    ("Freelance photographer — booking calendar, shot list generator, and gallery delivery tool", 3, "creative services", "freelancer"),
    ("Freelance copywriter — client brief intake, draft tracker, and invoice generator", 3, "creative services", "freelancer"),
    ("Freelance ghostwriter — manuscript tracker, chapter planner, and client feedback organizer", 3, "creative services", "freelancer"),
    ("Freelance translator — project tracker, glossary manager, and client billing assistant", 3, "creative services", "freelancer"),
    ("Freelance proofreader — job tracker, turnaround tracker, and invoice generator", 3, "creative services", "freelancer"),
    ("Freelance book editor — manuscript tracker, style guide assistant, and delivery notes generator", 3, "creative services", "freelancer"),
    ("Freelance journalist — story pitch tracker, source contact log, and expense tracker", 3, "creative services", "freelancer"),
    ("Freelance blogger-for-hire — client tracker, content calendar, and revision log", 3, "creative services", "freelancer"),
    ("Freelance SEO consultant — client keyword tracker, audit report generator, and ranking monitor", 3, "marketing", "freelancer"),
    ("Freelance content strategist — editorial calendar, brief generator, and performance tracker", 3, "marketing", "freelancer"),
    ("Freelance brand consultant — client discovery tracker, brand guideline generator, and deliverable tracker", 3, "marketing", "freelancer"),
    ("Freelance PR consultant — media contact tracker, pitch generator, and press coverage tracker", 3, "marketing", "freelancer"),
    ("Freelance communications consultant — client message planner, press release generator, and media list tracker", 3, "marketing", "freelancer"),
    ("Virtual assistant serving five clients — task tracker, weekly report generator, and client time tracker", 3, "services", "freelancer"),
    ("Online life coach — client session tracker, goal planner, and progress report generator", 3, "coaching", "freelancer"),
    ("Business coach — client call tracker, assignment generator, and progress report builder", 3, "coaching", "freelancer"),
    ("Executive coach — client session tracker, 360 feedback organizer, and action plan generator", 3, "coaching", "freelancer"),
    ("Career coach — client resume tracker, interview-prep planner, and session note organizer", 3, "coaching", "freelancer"),
    ("Sales coach — client roster, call analysis tracker, and weekly drill planner", 3, "coaching", "freelancer"),
    ("Marketing coach — client campaign tracker, content review planner, and strategy note organizer", 3, "coaching", "freelancer"),
    ("Productivity coach — client habit tracker, weekly review generator, and goal planner", 3, "coaching", "freelancer"),
    ("Health coach — client food log tracker, check-in planner, and progress reporter", 3, "coaching", "freelancer"),
    ("Online yoga teacher — class scheduler, member progress tracker, and sequence generator", 3, "fitness", "freelancer"),
    ("Online meditation teacher — session scheduler, student progress tracker, and weekly reflection generator", 3, "fitness", "freelancer"),
    ("Language tutor — student scheduler, curriculum planner, and progress report generator", 3, "education", "freelancer"),
    ("Online music teacher — student progress tracker, lesson planner, and recital planner", 3, "arts", "freelancer"),
    ("Online art teacher — student portfolio tracker, assignment generator, and critique scheduler", 3, "arts", "freelancer"),
    ("Creative writing coach — client manuscript tracker, assignment generator, and feedback organizer", 3, "coaching", "freelancer"),
    ("Acting coach — audition tracker, scene-study planner, and progress notes organizer", 3, "coaching", "freelancer"),
    ("Voice coach — student vocal progress tracker, exercise generator, and session scheduler", 3, "coaching", "freelancer"),
    ("Dance coach — student progress tracker, choreography planner, and showcase planner", 3, "coaching", "freelancer"),
    ("Etsy shop owner — product description generator, order tracker, and review analyzer", 3, "retail", "creator"),
    ("Shopify store owner — SKU tracker, abandoned cart email generator, and review follow-up assistant", 3, "retail", "creator"),
    ("Amazon FBA seller — inventory tracker, sales analyzer, and return issue tracker", 3, "retail", "creator"),
    ("eBay seller — listing tracker, repricer log, and shipping cost calculator", 3, "retail", "creator"),
    ("Poshmark reseller — inventory tracker, daily listing planner, and order fulfillment tracker", 3, "retail", "creator"),
    ("Vinyl record reseller — inventory tracker, condition log, and sales report generator", 3, "retail", "creator"),
    ("Sneaker reseller — inventory tracker, price watch tool, and shipment tracker", 3, "retail", "creator"),
    ("Vintage clothing reseller — inventory tracker, listing generator, and follower engagement tracker", 3, "retail", "creator"),
    ("Print-on-demand seller — design pipeline tracker, store catalog manager, and royalty summary generator", 3, "retail", "creator"),
    ("Digital product seller — product catalog, customer support tracker, and revenue report generator", 3, "retail", "creator"),
    ("Indie app developer — bug tracker, release notes generator, and user feedback analyzer", 3, "technology", "creator"),
    ("Indie game developer — bug tracker, playtester feedback collector, and release checklist generator", 3, "technology", "creator"),
    ("WordPress plugin developer — issue tracker, changelog generator, and customer support assistant", 3, "technology", "creator"),
    ("Shopify theme developer — client project tracker, changelog generator, and support request tracker", 3, "technology", "creator"),
    ("Freelance web developer — project tracker, client update generator, and invoicing tool", 3, "technology", "freelancer"),
    ("Freelance iOS developer — project tracker, TestFlight feedback organizer, and client update generator", 3, "technology", "freelancer"),
    ("Freelance Android developer — project tracker, beta tester feedback log, and client update generator", 3, "technology", "freelancer"),
    ("Freelance data analyst — client project tracker, report generator, and time-billing calculator", 3, "technology", "freelancer"),
    ("Freelance ML engineer — client project tracker, model experiment log, and delivery summary generator", 3, "technology", "freelancer"),
    ("No-code builder — client project tracker, deliverable log, and invoicing tool", 3, "technology", "freelancer"),
    ("Freelance wedding photographer — booking tracker, shot list generator, and album delivery manager", 3, "creative services", "freelancer"),
    ("Event videographer — booking calendar, shot list generator, and delivery timeline tracker", 3, "creative services", "freelancer"),
    ("Drone operator for real estate — job scheduler, flight log, and deliverable tracker", 3, "creative services", "freelancer"),
    ("Voice actor — casting tracker, audition log, and invoice generator", 3, "creative services", "freelancer"),
    ("Audiobook narrator — project tracker, recording session planner, and delivery log", 3, "creative services", "freelancer"),
    ("Jingle writer — project tracker, client feedback log, and invoice generator", 3, "creative services", "freelancer"),
    ("Sound designer — project tracker, asset library organizer, and delivery log", 3, "creative services", "freelancer"),
    ("Mixing engineer — project tracker, session notes organizer, and invoice generator", 3, "creative services", "freelancer"),
    ("Mastering engineer — project tracker, delivery log, and revision tracker", 3, "creative services", "freelancer"),
    ("Stock photographer — portfolio tracker, submission log, and earnings report generator", 3, "creative services", "creator"),
    ("Zine publisher — issue planner, subscriber manager, and print order tracker", 3, "creative services", "creator"),
    ("Self-published indie author with five titles — launch plan, reader email list, ad tracker, Amazon sales log, review tracker, editorial calendar, and royalty summary generator", 7, "creative services", "creator"),
    ("Self-published novelist — manuscript tracker, beta reader manager, and launch planner", 3, "creative services", "creator"),
    ("Children's book author — manuscript tracker, illustrator collaboration log, and school visit planner", 3, "creative services", "creator"),
    ("Comic artist — issue planner, commission tracker, and convention schedule", 3, "creative services", "creator"),
    ("Webcomic creator — update schedule, Patreon tier tracker, and reader feedback manager", 3, "creative services", "creator"),
    ("Fanfic writer — story tracker, reader comment log, and update schedule", 3, "creative services", "creator"),
    ("Romance novelist — manuscript tracker, release planner, and ARC reviewer manager", 3, "creative services", "creator"),
    ("Indie cookbook author — recipe library, photographer schedule, and launch planner", 3, "creative services", "creator"),
    ("Technical writer running a consultancy — client project tracker, document review log, and invoice generator", 3, "technical writing", "freelancer"),
    ("Affiliate marketer — offer tracker, content calendar, and earnings dashboard generator", 3, "marketing", "creator"),
    ("Dropshipper — order tracker, supplier communication log, and profit calculator", 3, "retail", "creator"),
    ("Fiverr seller — gig tracker, client queue manager, and delivery log", 3, "services", "freelancer"),
    ("Upwork freelancer — project tracker, proposal log, and time-billing tool", 3, "services", "freelancer"),
    ("Toptal developer — client project tracker, weekly report generator, and invoicing tool", 3, "technology", "freelancer"),
    ("UserTesting tester — session log, payout tracker, and feedback template manager", 3, "services", "freelancer"),
    ("Professional survey taker — panel tracker, payout log, and schedule planner", 3, "services", "freelancer"),
    ("Wyzant tutor — student scheduler, lesson planner, and progress report generator", 3, "education", "freelancer"),
    ("Teachable course creator — curriculum planner, student progress tracker, and email drip scheduler", 3, "education", "creator"),
    ("Udemy instructor — course outline planner, review tracker, and revenue report generator", 3, "education", "creator"),
    ("Kajabi course creator with three programs — curriculum planner, student progress tracker, launch planner, email sequence generator, affiliate tracker, testimonial collector, and revenue summary", 7, "education", "creator"),
    ("Patreon creator — tier planner, subscriber welcome sequence, and content calendar", 3, "creator economy", "creator"),
    ("Twitch affiliate — stream scheduler, sub tracker, and highlight clip library", 3, "creator economy", "creator"),
    ("Freelance user researcher — study tracker, participant scheduler, and report generator", 3, "research", "freelancer"),
    ("Freelance data viz designer — project tracker, dataset library, and delivery log", 3, "creative services", "freelancer"),
    ("Freelance motion designer — project tracker, client feedback log, and invoicing tool", 3, "creative services", "freelancer"),
    ("Freelance NFT artist — drop tracker, wallet allowlist manager, and royalty monitor", 3, "creative services", "creator"),
]


# ─────────────────────────────────────────────────────────────────────────────
# PROFESSIONALS & CORPORATE — 110 scenarios
# ─────────────────────────────────────────────────────────────────────────────

PROFESSIONALS = [
    ("I'm an HR manager and need a job description generator, a candidate tracker, and an onboarding checklist creator", 3, "hr", "corporate employee"),
    ("Sales manager running a team of eight — lead tracker, call script generator, and pipeline analyzer", 3, "sales", "corporate employee"),
    ("Financial advisor — client portfolio tracker, investment analyzer, and quarterly report generator", 3, "finance", "professional"),
    ("I'm a middle school teacher — lesson plan generator, student progress tracker, and assignment feedback assistant", 3, "education", "professional"),
    ("Family doctor — patient note summarizer, appointment tracker, and treatment plan generator", 3, "healthcare", "professional"),
    ("Project manager — task tracker, status report generator, and risk analyzer", 3, "management", "corporate employee"),
    ("Technical recruiter — job description generator, candidate scorer, and interview question creator", 3, "hr", "corporate employee"),
    ("Executive assistant supporting two VPs — meeting notes summarizer, task tracker, and email draft generator", 3, "administrative", "corporate employee"),
    ("Marketing manager at a SaaS company — campaign tracker, ROI analyzer, and content calendar generator", 3, "marketing", "corporate employee"),
    ("Product manager — feature request tracker, user feedback analyzer, and roadmap generator", 3, "product", "corporate employee"),
    ("Customer success manager with 40 accounts — health score tracker, renewal pipeline, and QBR report generator", 3, "customer success", "corporate employee"),
    ("Account executive closing enterprise deals — deal tracker, MEDDIC scorer, and follow-up email generator", 3, "sales", "corporate employee"),
    ("Business analyst — requirements tracker, stakeholder interview log, and spec generator", 3, "analytics", "corporate employee"),
    ("Data analyst on a small team — report request tracker, dashboard inventory, and stakeholder meeting notes", 3, "analytics", "corporate employee"),
    ("Compliance officer — policy tracker, audit log, and staff training planner", 3, "compliance", "corporate employee"),
    ("Risk manager — risk register, incident log, and quarterly report generator", 3, "risk", "corporate employee"),
    ("Operations manager for a 50-person company — inventory tracker, vendor log, and operations report generator", 3, "operations", "corporate employee"),
    ("Finance manager — budget tracker, vendor invoice log, and monthly close reporter", 3, "finance", "corporate employee"),
    ("Accounting manager — closing checklist tracker, reconciliation log, and staff schedule", 3, "finance", "corporate employee"),
    ("Controller at a small company — budget tracker, close process checklist, and board report generator", 3, "finance", "corporate employee"),
    ("Pediatrician in private practice — patient visit note summarizer, vaccination tracker, and parent communication assistant", 3, "healthcare", "professional"),
    ("Dermatologist — patient photo tracker, treatment plan generator, and appointment follow-up assistant", 3, "healthcare", "professional"),
    ("Cardiologist — patient history tracker, test-result summarizer, and referral tracker", 3, "healthcare", "professional"),
    ("Oncologist — patient treatment tracker, lab result summarizer, and family communication assistant", 3, "healthcare", "professional"),
    ("Psychiatrist — session note tracker, medication log, and patient follow-up assistant", 3, "healthcare", "professional"),
    ("Licensed therapist in private practice — session note summarizer, client intake forms, and outcome tracker", 3, "healthcare", "professional"),
    ("Psychologist — client assessment tracker, session note organizer, and progress report generator", 3, "healthcare", "professional"),
    ("Social worker with a large caseload — case tracker, visit log, and report generator", 3, "social services", "professional"),
    ("Dentist running a practice — appointment tracker, treatment plan generator, and insurance claim assistant", 3, "healthcare", "professional"),
    ("Optometrist — patient exam tracker, prescription log, and follow-up scheduler", 3, "healthcare", "professional"),
    ("Corporate attorney — matter tracker, document library, and time-tracking tool", 3, "legal", "professional"),
    ("Family law attorney — case tracker, document library, and client communication log", 3, "legal", "professional"),
    ("Criminal defense attorney — case tracker, document summarizer, and court date tracker", 3, "legal", "professional"),
    ("Paralegal — document production tracker, case calendar, and filing log", 3, "legal", "professional"),
    ("Legal assistant — scheduling tracker, document intake log, and client communication assistant", 3, "legal", "professional"),
    ("Court clerk — case calendar, filing log, and reporting tool", 3, "legal", "professional"),
    ("Court reporter freelancing — job schedule, transcript delivery tracker, and invoicing tool", 3, "legal", "freelancer"),
    ("Mediator — case tracker, session schedule, and outcome report generator", 3, "legal", "professional"),
    ("Arbitrator — case tracker, hearing schedule, and ruling drafting assistant", 3, "legal", "professional"),
    ("Contract attorney — engagement tracker, time log, and invoice generator", 3, "legal", "freelancer"),
    ("Elementary school teacher — lesson plan generator, student progress tracker, and parent communication assistant", 3, "education", "professional"),
    ("High school English teacher — assignment tracker, student feedback assistant, and grade book generator", 3, "education", "professional"),
    ("Adjunct college professor — syllabus planner, grading tracker, and office-hours scheduler", 3, "education", "professional"),
    ("Tenured professor — research log, grading tracker, and publication pipeline manager", 3, "education", "professional"),
    ("Graduate teaching assistant — section planner, grading tracker, and office-hours scheduler", 3, "education", "professional"),
    ("Librarian at a public library — inventory tracker, event planner, and patron communication assistant", 3, "education", "professional"),
    ("School counselor — student caseload tracker, IEP tracker, and parent communication log", 3, "education", "professional"),
    ("Elementary school principal — teacher roster, parent communication log, and event planner", 3, "education", "professional"),
    ("District superintendent — school performance tracker, board communication log, and budget tracker", 3, "education", "professional"),
    ("Curriculum developer — unit planner, assessment tracker, and teacher feedback log", 3, "education", "professional"),
    ("Hospital floor nurse — patient handoff tracker, medication log, and shift checklist generator", 3, "healthcare", "professional"),
    ("Charge nurse on a surgical unit — staff scheduler, patient acuity tracker, and shift handoff generator", 3, "healthcare", "professional"),
    ("Nurse practitioner in family practice — patient visit note summarizer, refill tracker, and follow-up scheduler", 3, "healthcare", "professional"),
    ("Physician assistant in urgent care — patient note tracker, prescription log, and handoff report generator", 3, "healthcare", "professional"),
    ("Medical assistant — intake form tracker, scheduling assistant, and referral log", 3, "healthcare", "professional"),
    ("Radiology tech — scan schedule, patient prep checklist, and study log", 3, "healthcare", "professional"),
    ("Pharmacy tech — prescription queue, inventory tracker, and insurance rejection tracker", 3, "healthcare", "professional"),
    ("Registered dietitian — patient meal plan generator, intake log, and follow-up scheduler", 3, "healthcare", "professional"),
    ("Speech-language pathologist — session note tracker, exercise planner, and progress report generator", 3, "healthcare", "professional"),
    ("Occupational therapist — session plan generator, progress tracker, and insurance assistance", 3, "healthcare", "professional"),
    ("Software engineer on a small team — PR review tracker, on-call runbook generator, and incident log", 3, "technology", "corporate employee"),
    ("Senior engineer — code review queue, mentoring notes tracker, and weekly update generator", 3, "technology", "corporate employee"),
    ("Staff engineer — cross-team initiative tracker, design review log, and status update generator", 3, "technology", "corporate employee"),
    ("Engineering manager — team 1:1 tracker, sprint planner, and weekly status generator", 3, "technology", "corporate employee"),
    ("CTO at a small startup — roadmap tracker, hiring pipeline manager, board update generator, investor relations tracker, engineer 1:1 manager, vendor relationship log, and quarterly review planner", 7, "technology", "corporate employee"),
    ("VP of Engineering — leadership 1:1 tracker, quarterly planning assistant, and exec update generator", 3, "technology", "corporate employee"),
    ("Director of engineering — team health tracker, project status dashboard, and hiring pipeline manager", 3, "technology", "corporate employee"),
    ("QA engineer — test plan generator, defect tracker, and release readiness report", 3, "technology", "corporate employee"),
    ("DevOps engineer — incident tracker, deployment log, and on-call runbook manager", 3, "technology", "corporate employee"),
    ("Site reliability engineer — alert tracker, postmortem log, and uptime report generator", 3, "technology", "corporate employee"),
    ("Sales rep at a SaaS company — pipeline tracker, outbound email generator, and follow-up assistant", 3, "sales", "corporate employee"),
    ("SDR — outbound prospect tracker, cold email generator, and call log assistant", 3, "sales", "corporate employee"),
    ("Business development rep — pipeline tracker, meeting note summarizer, and follow-up assistant", 3, "sales", "corporate employee"),
    ("Account executive — deal tracker, proposal generator, and contract redline log", 3, "sales", "corporate employee"),
    ("Enterprise AE — deal tracker, MEDDIC scorer, proposal generator, stakeholder map, contract log, renewal planner, and client success briefing", 7, "sales", "corporate employee"),
    ("Channel manager — partner pipeline, enablement planner, and quarterly business review generator", 3, "sales", "corporate employee"),
    ("Sales engineer — customer discovery log, demo prep tracker, and RFP response generator", 3, "sales", "corporate employee"),
    ("Pre-sales consultant — demo request tracker, RFP response library, and client follow-up assistant", 3, "sales", "corporate employee"),
    ("Customer trainer at a SaaS company — training session scheduler, attendee feedback tracker, and materials library", 3, "customer success", "corporate employee"),
    ("Customer onboarding specialist — new customer tracker, kickoff agenda generator, and success plan builder", 3, "customer success", "corporate employee"),
    ("CEO of a small company — board update generator, investor email tracker, company-wide comm planner, exec 1:1 tracker, hiring pipeline manager, quarterly OKR tracker, and press coverage log", 7, "leadership", "corporate employee"),
    ("COO — ops review tracker, cross-functional roadmap, vendor log, staff 1:1 tracker, quarterly planning assistant, hiring pipeline, and monthly board update generator", 7, "leadership", "corporate employee"),
    ("CFO at an early-stage company — budget tracker, investor update generator, cap table log, board meeting prep, hiring plan tracker, vendor contract log, and cash flow analyzer", 7, "leadership", "corporate employee"),
    ("VP of marketing — campaign tracker, content calendar, and monthly performance report generator", 3, "marketing", "corporate employee"),
    ("VP of sales — pipeline review tracker, rep 1:1 manager, and quarterly forecast generator", 3, "sales", "corporate employee"),
    ("VP of HR — hiring pipeline tracker, people program tracker, and exec update generator", 3, "hr", "corporate employee"),
    ("Head of people at a 100-person company — engagement survey tracker, benefits usage log, and manager enablement planner", 3, "hr", "corporate employee"),
    ("Head of communications — press inbound tracker, messaging calendar, and crisis comm playbook generator", 3, "communications", "corporate employee"),
    ("Head of compliance — policy tracker, audit log, and staff training tracker", 3, "compliance", "corporate employee"),
    ("General counsel at a midsize company — matter tracker, contract library, and board communication log", 3, "legal", "corporate employee"),
    ("Police officer filing reports — incident log, shift report generator, and community outreach planner", 3, "public safety", "professional"),
    ("Firefighter — shift log, training schedule tracker, and equipment inspection checklist", 3, "public safety", "professional"),
    ("Paramedic — shift log, patient care report generator, and equipment checklist tracker", 3, "public safety", "professional"),
    ("911 dispatcher — call log, resource tracker, and after-action report generator", 3, "public safety", "professional"),
    ("Air traffic controller trainee — shift log, simulator session tracker, and study planner", 3, "public safety", "professional"),
    ("Airline pilot — flight log, duty-day tracker, and training currency reminder", 3, "aviation", "professional"),
    ("Flight attendant — schedule tracker, duty log, and in-flight incident report generator", 3, "aviation", "professional"),
    ("Ship captain — voyage log, crew roster, and maintenance tracker", 3, "shipping", "professional"),
    ("Port manager — inbound cargo tracker, crew scheduler, and maintenance log", 3, "shipping", "professional"),
    ("Shipping coordinator — freight tracker, customs document log, and vendor communication assistant", 3, "shipping", "professional"),
    ("Real estate developer — project tracker, permit log, and investor update generator", 3, "real estate", "professional"),
    ("Architect at a small firm — project tracker, site visit log, and drawing revision tracker", 3, "architecture", "professional"),
    ("Civil engineer — project tracker, inspection log, and client report generator", 3, "engineering", "professional"),
    ("Structural engineer — project tracker, site visit log, and report generator", 3, "engineering", "professional"),
    ("Environmental engineer — site assessment tracker, compliance log, and client report generator", 3, "engineering", "professional"),
    ("Urban planner — project tracker, public comment log, and proposal generator", 3, "government", "professional"),
    ("City council member — constituent tracker, meeting agenda generator, and community update tool", 3, "government", "professional"),
    ("Mayor's office staffer — constituent case tracker, event planner, and briefing generator", 3, "government", "professional"),
    ("Nonprofit executive director — board meeting prep, fundraising tracker, and donor communication assistant", 3, "nonprofit", "professional"),
    ("Foundation program officer — grant pipeline tracker, site visit log, and outcome report generator", 3, "nonprofit", "professional"),
    ("Operations manager at a manufacturing plant — production tracker, maintenance log, and shift safety report generator", 3, "manufacturing", "corporate employee"),
    ("Supply chain manager — vendor tracker, shipment log, and delay analyzer", 3, "supply chain", "corporate employee"),
    ("Procurement manager — vendor tracker, PO log, and savings report generator", 3, "procurement", "corporate employee"),
    ("IT support lead — ticket tracker, asset log, and weekly summary generator", 3, "technology", "corporate employee"),
    ("Security analyst — incident log, vuln tracker, and weekly threat brief generator", 3, "security", "corporate employee"),
]


# ─────────────────────────────────────────────────────────────────────────────
# PERSONAL & LIFESTYLE — 110 scenarios
# ─────────────────────────────────────────────────────────────────────────────

PERSONAL = [
    ("I'm a parent of two toddlers and need a child milestone tracker, a daily activity planner, and a doctor visit log", 3, "family", "parent"),
    ("Parent of three teens — chore tracker, extracurricular calendar, and homework progress tracker", 3, "family", "parent"),
    ("We homeschool our two kids — curriculum planner, progress tracker, and field trip planner", 3, "education", "parent"),
    ("Foster parent — placement log, appointment tracker, and communication log with caseworkers", 3, "family", "parent"),
    ("Adoptive parent navigating an open adoption — contact log, milestone tracker, and paperwork checklist", 3, "family", "parent"),
    ("Expecting first baby — pregnancy tracker, nursery planner, and hospital bag checklist generator", 3, "family", "parent"),
    ("Single parent — monthly budget tracker, kids' activity planner, and meal planner", 3, "family", "parent"),
    ("Grandparent babysitting two grandkids — daily schedule generator, activity idea generator, and medication reminder", 3, "family", "parent"),
    ("Blended family with four kids — shared calendar, chore tracker, and weekly budget planner", 3, "family", "parent"),
    ("Parent of a child with autism — therapy tracker, sensory-friendly activity planner, and school communication log", 3, "family", "parent"),
    ("High school junior — homework tracker, college application planner, and extracurricular log", 3, "education", "student"),
    ("College freshman — class schedule, assignment tracker, and campus event planner", 3, "education", "student"),
    ("Grad student in psychology — research log, class tracker, and thesis planner", 3, "education", "student"),
    ("Medical student on rotations — rotation tracker, study schedule, and board prep planner", 3, "education", "student"),
    ("Law student — case reading tracker, class notes organizer, and bar prep planner", 3, "education", "student"),
    ("PhD student in biology — experiment log, literature tracker, and dissertation planner", 3, "education", "student"),
    ("Online MBA student — class schedule, group project tracker, and networking log", 3, "education", "student"),
    ("Returning adult student — class schedule, family calendar, and study planner", 3, "education", "student"),
    ("Transfer student — class schedule, credit transfer tracker, and campus orientation planner", 3, "education", "student"),
    ("Gap year traveler — itinerary planner, expense tracker, and journal log", 3, "travel", "personal"),
    ("Home cook — recipe library, weekly meal planner, and grocery list generator", 3, "food", "personal"),
    ("Weekend batch cooker — meal prep planner, leftovers tracker, and grocery list generator", 3, "food", "personal"),
    ("Amateur baker — recipe library, bake schedule planner, and inventory tracker", 3, "food", "personal"),
    ("Backyard BBQ enthusiast — recipe library, grill event planner, and smoker session log", 3, "food", "personal"),
    ("Wine collector — cellar inventory, tasting notes log, and pairing suggestion tool", 3, "food", "personal"),
    ("Home brewer — recipe log, fermentation tracker, and tasting notes organizer", 3, "food", "personal"),
    ("Coffee snob — home bean inventory, brew log, and grind setting tracker", 3, "food", "personal"),
    ("Tea aficionado — tea inventory, brewing log, and tasting notes organizer", 3, "food", "personal"),
    ("Foodie traveler — restaurant wishlist, trip tracker, and food photo archive", 3, "food", "personal"),
    ("Amateur marathon runner — training plan, weekly mileage tracker, and race calendar", 3, "fitness", "personal"),
    ("Triathlete in training — workout log, nutrition tracker, and race planner", 3, "fitness", "personal"),
    ("Cyclist clocking 150 miles a week — ride log, bike maintenance tracker, and route planner", 3, "fitness", "personal"),
    ("Rock climber — climb log, training plan, and gear inventory", 3, "fitness", "personal"),
    ("Hiker tackling long trails — trail log, gear inventory, and food plan generator", 3, "fitness", "personal"),
    ("Weekend backpacker — trip planner, gear list generator, and trail journal", 3, "travel", "personal"),
    ("Skier — mountain visit log, equipment inventory, and conditions tracker", 3, "travel", "personal"),
    ("Snowboarder — trip log, gear inventory, and run tracker", 3, "travel", "personal"),
    ("Surfer — surf session log, gear inventory, and tide and wind tracker", 3, "travel", "personal"),
    ("First-time dog owner — vet visit tracker, feeding schedule, and training log", 3, "pets", "personal"),
    ("Cat owner with three cats — vet tracker, feeding schedule, and litter box rotation log", 3, "pets", "personal"),
    ("Multi-pet household — feeding scheduler, vet tracker, and grooming calendar", 3, "pets", "personal"),
    ("Aquarium hobbyist — fish inventory, water test log, and feeding schedule", 3, "pets", "personal"),
    ("Bird owner — health tracker, feeding schedule, and vet appointment reminder", 3, "pets", "personal"),
    ("Exotic pet owner (reptiles) — feeding schedule, temperature log, and vet tracker", 3, "pets", "personal"),
    ("Horse owner — stable visit log, feeding tracker, and vet/farrier calendar", 3, "pets", "personal"),
    ("Rabbit owner — feeding schedule, vet tracker, and playtime log", 3, "pets", "personal"),
    ("Reptile keeper — feeding log, enclosure temperature tracker, and vet reminder", 3, "pets", "personal"),
    ("Home gardener with a big backyard plot — planting schedule, harvest tracker, and pest log", 3, "gardening", "personal"),
    ("Container gardener on a balcony — plant inventory, watering schedule, and harvest log", 3, "gardening", "personal"),
    ("Urban gardener — raised bed planner, watering schedule, and harvest tracker", 3, "gardening", "personal"),
    ("Hydroponics hobbyist — nutrient schedule, harvest log, and system maintenance tracker", 3, "gardening", "personal"),
    ("Houseplant collector with 80 plants — watering schedule, repot tracker, and pest log", 3, "gardening", "personal"),
    ("Orchid grower — watering schedule, fertilizing log, and bloom tracker", 3, "gardening", "personal"),
    ("Vegetable gardener — planting schedule, harvest log, and preservation planner", 3, "gardening", "personal"),
    ("Herb gardener — planting tracker, harvest log, and recipe matcher", 3, "gardening", "personal"),
    ("Rose gardener — pruning schedule, pest log, and bloom tracker", 3, "gardening", "personal"),
    ("Bonsai enthusiast — watering schedule, pruning log, and repot tracker", 3, "gardening", "personal"),
    ("First-time homebuyer — house hunting tracker, mortgage calculator, and inspection checklist", 3, "real estate", "personal"),
    ("Move-up buyer upgrading to a bigger house — house hunting tracker, contingency planner, and move checklist", 3, "real estate", "personal"),
    ("Downsizer selling the family home — decluttering tracker, staging planner, and move checklist", 3, "real estate", "personal"),
    ("Empty nester with a big home — maintenance tracker, decluttering planner, and rental income calculator", 3, "real estate", "personal"),
    ("Retiree rebuilding a routine — daily schedule generator, doctor appointment tracker, and hobby log", 3, "lifestyle", "personal"),
    ("Pre-retiree doing final planning — retirement budget tracker, pension reminder, and social calendar", 3, "finance", "personal"),
    ("Snowbird with two residences — travel calendar, utility tracker, and packing list generator", 3, "lifestyle", "personal"),
    ("RV owner traveling full time — trip planner, maintenance tracker, and campground reviewer", 3, "travel", "personal"),
    ("Tiny house dweller — utility tracker, space inventory, and repair log", 3, "lifestyle", "personal"),
    ("Van lifer — travel log, van maintenance tracker, and expense planner", 3, "travel", "personal"),
    ("Mid-career job seeker — application tracker, resume optimizer, and interview prep assistant", 3, "career", "personal"),
    ("Career changer switching industries — application tracker, skills gap analyzer, and interview prep assistant", 3, "career", "personal"),
    ("Recent graduate — application tracker, cover letter generator, and networking log", 3, "career", "personal"),
    ("Parent returning to work — application tracker, childcare scheduler, and interview prep planner", 3, "career", "personal"),
    ("Military veteran transitioning — resume optimizer, benefits tracker, and job application log", 3, "career", "personal"),
    ("Freshly laid-off professional — job search tracker, severance budget planner, and emotional check-in journal", 3, "career", "personal"),
    ("Unhappy employee quietly looking — stealth job search tracker, networking log, and interview prep assistant", 3, "career", "personal"),
    ("Consultant between gigs — prospect tracker, engagement log, and income planner", 3, "career", "personal"),
    ("Seasonal worker planning the off-season — income log, gap plan, and next-season application tracker", 3, "career", "personal"),
    ("Gig worker juggling three apps — earnings log, expense tracker, and schedule planner", 3, "career", "personal"),
    ("Budget-conscious saver — expense tracker, savings goal tracker, and monthly budget generator", 3, "finance", "personal"),
    ("FIRE-pursuing saver — net worth tracker, savings rate analyzer, and investment portfolio tracker", 3, "finance", "personal"),
    ("Dividend-focused investor — portfolio tracker, dividend calendar, and reinvestment planner", 3, "finance", "personal"),
    ("Index-investor with a Roth IRA and brokerage — account tracker, rebalancing planner, and annual contribution log", 3, "finance", "personal"),
    ("Crypto enthusiast — wallet tracker, transaction log, and staking rewards monitor", 3, "finance", "personal"),
    ("Day trader hobbyist — trade journal, P&L tracker, and strategy backtest log", 3, "finance", "personal"),
    ("Small real estate investor with three rental homes — income tracker, maintenance log, and tenant communication tool", 3, "real estate", "personal"),
    ("Small-check angel investor — investment tracker, deal log, and portfolio update planner", 3, "finance", "personal"),
    ("Options trader — trade journal, P&L tracker, and earnings calendar", 3, "finance", "personal"),
    ("Bond investor with a ladder — maturity tracker, yield calculator, and reinvestment planner", 3, "finance", "personal"),
    ("Fitness beginner — workout planner, progress tracker, and motivation journal", 3, "fitness", "personal"),
    ("Yoga practitioner — home practice tracker, class schedule, and progress journal", 3, "fitness", "personal"),
    ("CrossFit athlete — WOD log, 1RM tracker, and competition planner", 3, "fitness", "personal"),
    ("Pilates enthusiast — class schedule, progress log, and instructor rotation tracker", 3, "fitness", "personal"),
    ("Martial artist training for a belt test — technique tracker, sparring log, and test prep planner", 3, "fitness", "personal"),
    ("Dancer training for auditions — class schedule, audition tracker, and injury log", 3, "fitness", "personal"),
    ("Choreographer working on a showcase — rehearsal planner, cast tracker, and costume log", 3, "arts", "personal"),
    ("Amateur runner focused on flexibility — stretch log, run log, and recovery tracker", 3, "fitness", "personal"),
    ("Powerlifter — training log, meet prep tracker, and nutrition planner", 3, "fitness", "personal"),
    ("Amateur bodybuilder prepping for a show — workout log, nutrition tracker, and posing practice log", 3, "fitness", "personal"),
    ("Comic book collector with 2000 issues — inventory tracker, wishlist manager, and grade log", 3, "hobby", "personal"),
    ("Trading card collector — inventory log, wishlist, and trade tracker", 3, "hobby", "personal"),
    ("Stamp collector — inventory tracker, wishlist, and exhibition planner", 3, "hobby", "personal"),
    ("Coin collector — inventory tracker, grade log, and wishlist manager", 3, "hobby", "personal"),
    ("Vinyl record collector — inventory tracker, wishlist, and play log", 3, "hobby", "personal"),
    ("Vintage watch collector — inventory log, service tracker, and appraisal log", 3, "hobby", "personal"),
    ("Amateur photographer — shot log, gear inventory, and portfolio organizer", 3, "hobby", "personal"),
    ("Amateur astronomer — observation log, equipment inventory, and sky event planner", 3, "hobby", "personal"),
    ("Amateur radio operator — contact log, equipment tracker, and contest planner", 3, "hobby", "personal"),
    ("Chess player rated 1600 — game log, opening repertoire, and tournament planner", 3, "hobby", "personal"),
    ("First-time investor — portfolio tracker, monthly budget, and investment idea log", 3, "finance", "personal"),
    ("Thinking about early retirement — savings tracker, FIRE calculator, and part-time income planner", 3, "finance", "personal"),
    ("Recently divorced and starting over financially — new budget tracker, debt payoff planner, and savings goal tracker", 3, "finance", "personal"),
    ("New couple moving in together — joint budget, shared chore tracker, and shared grocery list generator", 3, "family", "personal"),
    ("Planning a wedding on a tight budget — vendor tracker, guest list manager, and budget analyzer", 3, "events", "personal"),
    ("Planning a milestone birthday — guest tracker, gift log, and venue planner", 3, "events", "personal"),
]


# ─────────────────────────────────────────────────────────────────────────────
# NONPROFITS & EDUCATION — 110 scenarios
# ─────────────────────────────────────────────────────────────────────────────

NONPROFIT_EDUCATION = [
    ("Small nonprofit serving local families — donor tracker, grant proposal generator, and volunteer scheduler", 3, "nonprofit", "nonprofit staff"),
    ("Mid-size nonprofit — donor tracker, grant pipeline manager, and event planner", 3, "nonprofit", "nonprofit staff"),
    ("Large nonprofit with ten staff — donor database, grant tracker, volunteer scheduler, event planner, program outcome tracker, board communication log, and annual report generator", 7, "nonprofit", "nonprofit staff"),
    ("International NGO with field offices — grant pipeline, field report tracker, and donor communication assistant", 3, "nonprofit", "nonprofit staff"),
    ("Community foundation — grant pipeline tracker, site visit log, and donor stewardship planner", 3, "nonprofit", "nonprofit staff"),
    ("Family foundation — grant tracker, board meeting prep, and site visit log", 3, "nonprofit", "nonprofit staff"),
    ("Private foundation — grant review tracker, program officer log, and board update generator", 3, "nonprofit", "nonprofit staff"),
    ("Corporate foundation administered internally — employee volunteer tracker, matching gift log, and community partner manager", 3, "nonprofit", "nonprofit staff"),
    ("Giving circle with 30 members — member contribution tracker, grant pipeline, and meeting planner", 3, "nonprofit", "nonprofit staff"),
    ("Crowdfunding campaign runner — backer tracker, update planner, and reward fulfillment log", 3, "nonprofit", "nonprofit staff"),
    ("Public elementary school office manager — student records tracker, parent communication log, and event planner", 3, "education", "school staff"),
    ("Charter school front office — student attendance tracker, parent volunteer log, and fundraising tracker", 3, "education", "school staff"),
    ("Private school admissions office — inquiry tracker, application log, and open house planner", 3, "education", "school staff"),
    ("Montessori school office — student progress tracker, parent communication log, and material inventory", 3, "education", "school staff"),
    ("Catholic school office — student attendance, parent communication, and sacrament schedule", 3, "education", "school staff"),
    ("Boarding school — student dorm tracker, parent communication log, and weekend activity planner", 3, "education", "school staff"),
    ("International school — student record tracker, parent communication across time zones, and event planner", 3, "education", "school staff"),
    ("Online school — student progress tracker, attendance log, and parent communication assistant", 3, "education", "school staff"),
    ("Homeschool cooperative — member family tracker, class scheduler, and field trip planner", 3, "education", "parent"),
    ("Community college program director — student roster, syllabus tracker, and advisor communication log", 3, "education", "school staff"),
    ("State university department — faculty schedule, course catalog tracker, and student advising log", 3, "education", "school staff"),
    ("Liberal arts college dean's office — faculty tracker, student advising log, and event planner", 3, "education", "school staff"),
    ("Research university lab — grant tracker, publication pipeline, and undergrad researcher log", 3, "education", "school staff"),
    ("Business school career services — employer tracker, student resume log, and event planner", 3, "education", "school staff"),
    ("Medical school admissions — applicant tracker, interview scheduler, and committee meeting planner", 3, "education", "school staff"),
    ("Law school faculty office — course tracker, office hours planner, and student meeting log", 3, "education", "school staff"),
    ("Engineering school capstone coordinator — project tracker, industry sponsor log, and showcase planner", 3, "education", "school staff"),
    ("Graduate program director — applicant tracker, qualifying exam planner, and dissertation tracker", 3, "education", "school staff"),
    ("Continuing ed program — student roster, instructor scheduler, and course feedback tracker", 3, "education", "school staff"),
    ("Protestant church office — member tracker, event planner, and donation log", 3, "faith-based", "nonprofit staff"),
    ("Catholic parish office — sacrament tracker, event planner, and volunteer coordinator", 3, "faith-based", "nonprofit staff"),
    ("Synagogue — member tracker, event planner, and donation log", 3, "faith-based", "nonprofit staff"),
    ("Mosque — member tracker, event planner, and volunteer coordinator", 3, "faith-based", "nonprofit staff"),
    ("Hindu temple — event planner, volunteer tracker, and donation log", 3, "faith-based", "nonprofit staff"),
    ("Meditation center — class schedule tracker, member tracker, and donation log", 3, "faith-based", "nonprofit staff"),
    ("Spiritual retreat center — retreat planner, guest tracker, and housekeeping scheduler", 3, "faith-based", "nonprofit staff"),
    ("Interfaith council — member org tracker, event planner, and newsletter planner", 3, "faith-based", "nonprofit staff"),
    ("Faith-based nonprofit — donor tracker, volunteer log, and program outcome tracker", 3, "nonprofit", "nonprofit staff"),
    ("Religious school office — student roster, parent communication log, and volunteer scheduler", 3, "education", "school staff"),
    ("Regional food bank — donation tracker, volunteer scheduler, inventory manager, partner agency tracker, delivery route planner, fundraising tracker, and annual report generator", 7, "nonprofit", "nonprofit staff"),
    ("Soup kitchen — volunteer scheduler, inventory tracker, and daily meal planner", 3, "nonprofit", "nonprofit staff"),
    ("Homeless shelter — resident tracker, volunteer log, and donation tracker", 3, "nonprofit", "nonprofit staff"),
    ("Women's shelter — resident tracker, resource referral log, and volunteer scheduler", 3, "nonprofit", "nonprofit staff"),
    ("Disaster relief org — volunteer deployment tracker, supply inventory, and field report log", 3, "nonprofit", "nonprofit staff"),
    ("Refugee resettlement org — client intake tracker, housing log, and volunteer scheduler", 3, "nonprofit", "nonprofit staff"),
    ("Community kitchen — volunteer scheduler, ingredient inventory, and guest log", 3, "nonprofit", "nonprofit staff"),
    ("Community fridge org — volunteer schedule, donation log, and maintenance tracker", 3, "nonprofit", "nonprofit staff"),
    ("Meals-on-wheels program — delivery route planner, client tracker, and volunteer scheduler", 3, "nonprofit", "nonprofit staff"),
    ("Clothing closet — donation intake tracker, client visit log, and volunteer scheduler", 3, "nonprofit", "nonprofit staff"),
    ("Animal shelter — intake tracker, adoption tracker, volunteer scheduler, foster tracker, medical log, donor communication, and annual report generator", 7, "nonprofit", "nonprofit staff"),
    ("Wildlife rescue — intake log, volunteer scheduler, and release tracker", 3, "nonprofit", "nonprofit staff"),
    ("Dog rescue — intake tracker, foster log, and adoption pipeline", 3, "nonprofit", "nonprofit staff"),
    ("Cat rescue — intake tracker, foster log, and adoption pipeline", 3, "nonprofit", "nonprofit staff"),
    ("Farm animal sanctuary — resident animal tracker, feeding schedule, and donor communication log", 3, "nonprofit", "nonprofit staff"),
    ("Marine mammal rescue — intake log, release tracker, and volunteer scheduler", 3, "nonprofit", "nonprofit staff"),
    ("Raptor rehab center — patient intake tracker, feeding log, and release planner", 3, "nonprofit", "nonprofit staff"),
    ("Reptile rescue — intake tracker, housing log, and adoption planner", 3, "nonprofit", "nonprofit staff"),
    ("Pet adoption event organizer — event planner, animal roster, and volunteer scheduler", 3, "nonprofit", "nonprofit staff"),
    ("Spay and neuter nonprofit — appointment tracker, vet volunteer log, and donation tracker", 3, "nonprofit", "nonprofit staff"),
    ("Youth soccer league — team roster, game scheduler, and parent communication log", 3, "youth sports", "coach"),
    ("Little League baseball team — player roster, practice planner, and game day coordinator", 3, "youth sports", "coach"),
    ("AYSO soccer club — team rosters, referee scheduler, and parent communication log", 3, "youth sports", "coach"),
    ("Youth swim team coach — meet schedule, practice planner, and progress tracker", 3, "youth sports", "coach"),
    ("Youth climbing team — practice planner, competition tracker, and parent communication log", 3, "youth sports", "coach"),
    ("School robotics team — build schedule, parts inventory, and competition planner", 3, "education", "coach"),
    ("Debate team coach — tournament scheduler, practice planner, and student prep tracker", 3, "education", "coach"),
    ("Academic decathlon coach — study planner, team roster, and competition tracker", 3, "education", "coach"),
    ("Science Olympiad coach — event tracker, student practice planner, and competition schedule", 3, "education", "coach"),
    ("Chess club coach — practice planner, tournament scheduler, and rating tracker", 3, "education", "coach"),
    ("Community theater — season planner, audition tracker, and volunteer schedule", 3, "arts", "nonprofit staff"),
    ("Youth theater — audition tracker, rehearsal schedule, and parent communication log", 3, "arts", "nonprofit staff"),
    ("Ballet school — class schedule, recital planner, and parent communication log", 3, "arts", "school staff"),
    ("Music school nonprofit — student tracker, recital planner, and donor communication log", 3, "arts", "nonprofit staff"),
    ("Arts council — grant pipeline, member tracker, and event planner", 3, "nonprofit", "nonprofit staff"),
    ("Public library — event planner, member outreach log, and volunteer scheduler", 3, "education", "nonprofit staff"),
    ("Rural library — event planner, bookmobile tracker, and community partner log", 3, "education", "nonprofit staff"),
    ("Academic library — research request tracker, faculty liaison log, and event planner", 3, "education", "nonprofit staff"),
    ("Prison library program — volunteer scheduler, inventory tracker, and request log", 3, "education", "nonprofit staff"),
    ("Literacy council — tutor scheduler, student progress tracker, and volunteer training planner", 3, "education", "nonprofit staff"),
    ("Alumni association — event planner, donation tracker, and member communication log", 3, "education", "nonprofit staff"),
    ("PTO / PTA — fundraising tracker, event planner, and volunteer scheduler", 3, "education", "parent"),
    ("Booster club for a high school team — fundraising tracker, game day coordinator, and sponsorship log", 3, "education", "parent"),
    ("Student council advisor — meeting planner, event tracker, and election organizer", 3, "education", "school staff"),
    ("Student newspaper advisor — story pipeline, issue schedule, and publication tracker", 3, "education", "school staff"),
    ("Yearbook advisor — page assignment tracker, photo library, and deadline planner", 3, "education", "school staff"),
    ("College admissions counselor — student caseload, application tracker, and college visit planner", 3, "education", "school staff"),
    ("Career services office — employer partner tracker, student resume log, and event planner", 3, "education", "school staff"),
    ("Financial aid office — applicant tracker, communication log, and appeal case tracker", 3, "education", "school staff"),
    ("Study abroad office — applicant tracker, partner university log, and orientation planner", 3, "education", "school staff"),
    ("Scouts troop — member tracker, meeting planner, and fundraising log", 3, "youth", "nonprofit staff"),
    ("Girl Scouts troop — member tracker, cookie sale planner, and badge tracker", 3, "youth", "nonprofit staff"),
    ("4-H club — member tracker, project log, and county fair planner", 3, "youth", "nonprofit staff"),
    ("FFA chapter — member tracker, project planner, and competition schedule", 3, "youth", "nonprofit staff"),
    ("Boys & Girls Club — member tracker, programming planner, and volunteer scheduler", 3, "youth", "nonprofit staff"),
    ("YMCA program — member tracker, class scheduler, and event planner", 3, "youth", "nonprofit staff"),
    ("YWCA program — member tracker, program planner, and volunteer scheduler", 3, "youth", "nonprofit staff"),
    ("After-school program — student roster, activity planner, and parent communication log", 3, "youth", "nonprofit staff"),
    ("Summer camp — camper tracker, counselor scheduler, and activity planner", 3, "youth", "nonprofit staff"),
    ("Day camp — camper roster, daily activity planner, and parent communication log", 3, "youth", "nonprofit staff"),
    ("Volunteer fire department — roster tracker, training scheduler, and equipment log", 3, "public safety", "nonprofit staff"),
    ("Volunteer rescue squad — roster, training log, and equipment maintenance tracker", 3, "public safety", "nonprofit staff"),
    ("Neighborhood watch group — member tracker, incident log, and meeting planner", 3, "community", "nonprofit staff"),
    ("Homeowners' association — member roster, meeting planner, and violation tracker", 3, "community", "nonprofit staff"),
    ("HOA block captain — neighbor directory, issue tracker, and welcome-packet planner", 3, "community", "personal"),
    ("Senior center — member tracker, program planner, and volunteer scheduler", 3, "nonprofit", "nonprofit staff"),
    ("Assisted living activity coordinator — resident activity tracker, volunteer scheduler, and family communication log", 3, "healthcare", "nonprofit staff"),
    ("Hospice volunteer coordinator — volunteer scheduler, family contact log, and training tracker", 3, "healthcare", "nonprofit staff"),
    ("Veterans service org — member tracker, benefit-claim support log, and event planner", 3, "nonprofit", "nonprofit staff"),
    ("Disabled veterans group — member tracker, resource referral log, and event planner", 3, "nonprofit", "nonprofit staff"),
    ("University alumni chapter — member tracker, event planner, and fundraising log", 3, "education", "nonprofit staff"),
    ("PhD alumni network — member tracker, event planner, and mentorship log", 3, "education", "nonprofit staff"),
    ("Historical society — collection tracker, event planner, and membership log", 3, "nonprofit", "nonprofit staff"),
    ("Tribal nonprofit program — member tracker, program outcome log, and event planner", 3, "nonprofit", "nonprofit staff"),
    ("Children's hospital foundation — donor tracker, event planner, and grant tracker", 3, "nonprofit", "nonprofit staff"),
    ("University department running a big annual research conference — abstract tracker, registration manager, session planner, speaker outreach log, sponsorship tracker, program generator, and budget tracker", 7, "education", "school staff"),
]


# Flat pool — 550 scenarios total. Concatenated so get_ecosystem_scenarios()
# can random.sample() across everything in one pass. Any SMALL_BUSINESS
# entries removed/added later will automatically flow through.
_RAW_POOL = (
    SMALL_BUSINESS
    + CREATORS
    + PROFESSIONALS
    + PERSONAL
    + NONPROFIT_EDUCATION
)

ECOSYSTEM_SCENARIOS: list[dict] = [
    {
        "description":         desc,
        "suggested_app_count": count,
        "industry":            industry,
        "user_type":           user_type,
    }
    for desc, count, industry, user_type in _RAW_POOL
]


def get_ecosystem_scenarios(count: int = 5) -> list[dict]:
    """
    Return `count` ecosystem scenarios drawn without repetition from the
    550-entry pool. Caller pays no attention to suggested_app_count —
    the Ecosystem Tester UI picks the app_count (3 or 7) batch-wide.
    """
    if count <= 0:
        return []
    sample = random.sample(ECOSYSTEM_SCENARIOS, min(count, len(ECOSYSTEM_SCENARIOS)))
    # Shallow-copy each dict so callers can mutate freely without poisoning the pool.
    return [dict(s) for s in sample]


def pool_size() -> int:
    """Exposed for tests / sanity checks."""
    return len(ECOSYSTEM_SCENARIOS)
